#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git gofmt pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep -v '\.pb.go$'| grep '\.go$')

[ -z "$gofiles" ] && exit 0

# Format ALL of the unformatted files automatically
unformatted=$(gofmt -l $gofiles)
echo >&2 "Formatting go files in this commit."
for fn in $unformatted; do
	echo >&2 "formatting $PWD/$fn"
	gofmt -s -w $PWD/$fn
    git add $PWD/$fn
done

which golint>/dev/null 2>&1
if [ $? -ne 0 ]; then
	go get -u github.com/x/lint/golint
fi

has_error=0
for file in ${gofiles}; do
    golint -set_exit_status ${file}
    if [ $? -ne 0 ]; then
        has_error=1
    fi
done

if [ ${has_error} -ne 0 ]; then
    echo "One or more linter errors. Fix them and try again."
    exit 1
fi

go vet -race $PWD/...
if [ $? -ne 0 ]; then
	echo "go vet failure, correct errors"
	exit 1
fi

which misspell>/dev/null 2>&1
if [ $? -ne 0 ]; then
	go get -u github.com/client9/misspell/cmd/misspell
fi

# this is setup to fail the commit due to misspellings
echo "executing misspell"
misspell -error .

which ineffassign>/dev/null 2>&1
if [ $? -ne 0 ]; then
	go get -u github.com/gordonklaus/ineffassign
fi

echo "executing ineffassign"
ineffassign .

which errcheck>/dev/null 2>&1
if [ $? -ne 0 ]; then
	go get -u github.com/kisielk/errcheck
fi

echo "executing errcheck"
errcheck ./...

which gosec>/dev/null 2>&1
if [ $? -ne 0 ]; then
	go get -u github.com/securego/gosec/cmd/gosec
fi

# This is setup to NOT fail a commit. Just informational for now.
echo "executing gosec"
gosec -no-fail -quiet ./...

which staticcheck>/dev/null 2>&1
if [ $? -ne 0 ]; then
	go get -u honnef.co/go/tools/cmd/staticcheck 
fi

# This is setup to NOT fail a commit. Just informational for now.
echo "executing staticcheck"
staticcheck -tests=0 -fail ./...

go mod tidy
git add go.mod
git add go.sum
