#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git gofmt pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep -v '\.pb.go$'| grep '\.go$')

[ -z "$gofiles" ] && exit 0

# Format ALL of the unformatted files automatically
unformatted=$(gofmt -l $gofiles)
echo >&2 "Formatting go files in this commit."
for fn in $unformatted; do
	echo >&2 "formatting $PWD/$fn"
	gofmt -s -w $PWD/$fn
    git add $PWD/$fn
done

has_error=0
for file in ${gofiles}; do
    golint -set_exit_status ${file}
    if [ $? -ne 0 ]; then
        has_error=1
    fi
done

for file in ${gofiles}; do
    go vet -race ${file}
    if [ $? -ne 0 ]; then
        has_error=1
    fi
done

if [ ${has_error} -ne 0 ]; then
    echo "One or more errors. Fix them and try again."
    exit 1
fi
