#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git gofmt pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

[ -z "$gofiles" ] && exit 0

# Format ALL of the unformatted files automatically
unformatted=$(gofmt -l $gofiles)
echo >&2 "Formatting go files in this commit."
for fn in $unformatted; do
	echo >&2 "formatting $PWD/$fn"
	gofmt -s -w $PWD/$fn
    git add $PWD/$fn
done

# LINTER HERE
for fn in $gofiles;
# LINTER HERE
done

if ! go vet $PWD/...
then
	echo "go vet failure, correct errors"
	exit 1
fi